services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: python -m http.server 8000 --directory src
